### ISSUE TITLE
A few UX stuff

### ISSUE THREAD

**Issue by adrien-candiotti** [GridSound/gridsound.github.io#6]
- Zoom should not be the basic behaviour for the mouse scroll. A modifier like CTRL should be applied
- Space is generally a shortcut to play/pause in DAWs

**Comment by Mr21** [comment]
Currently **play/pause** is binded on `enter` and **stop** on `backspace`.
But yeah... every single other app use `space`... I will change that soon.

What can be a good replacement for the actual `space` so?
The actual space is inspired by Photoshop for example.

And to zoom we can make :
* `Ctrl (hold)` + `Scroll` or
* `Ctrl (hold)` + `left/right click` or
* `Z` + `Scroll` or
* `Z` + `left/right click`

There are several problems when we start to hold `Ctrl` and leave the window... The `Ctrl` keyup event is not fired, and the Zoom will stay :/
But normally, the scroll is not by default for the zoom.

Sorry for the delay, I didnt see that issue :/

**Comment by Mr21** [comment]
Done

**Hand** tool: `H` or hold `Alt`
**Play** / **Stop**: `space`
**Pause**: `Ctrl+space`
